import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir} from 'node:fs/promises';
await mkdir('.build/tests',{recursive:true});
await build({entryPoints:['engine/player.ts'],outfile:'.build/tests/files.mjs',bundle:true,platform:'node',format:'esm',alias:{'@dreamfactory/engine':'./vendor/dreamrefactory/engine/src'},tsconfig:'vendor/dreamrefactory/tsconfig.json'});
const {Files}=await import('../.build/tests/files.mjs');
test('disc-specific resources win and shared files fall back to the other disc',()=>{
 const source={'first-room':new Uint8Array([11]),'second-room':new Uint8Array([22]),'shared':new Uint8Array([33])};
 globalThis.__native=(method,args)=>source[JSON.parse(args).path]?.slice().buffer??null;
 const files=new Files({'1/room.set':'first-room','2/room.set':'second-room','1/shared.shp':'shared'});
 assert.deepEqual([...files.provide('ROOM.SET')],[11]);
 files.setDisc(2);
 assert.deepEqual([...files.provide('Titanic2:data:room.set')],[22]);
 assert.deepEqual([...files.provide('shared.shp')],[33]);
 files.setDisc(1);
 assert.deepEqual([...files.provide('room.set')],[11]);
 assert.equal(files.provide('missing.mov'),null);
 assert.equal(files.evict('room.set'),1);
 assert.equal(files.has('room.set'),false);
});
