import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
await mkdir('.build/tests',{recursive:true});
await build({entryPoints:['tests/save-codec-entry.ts'],bundle:true,platform:'node',format:'esm',outfile:'.build/tests/save-codec.mjs',plugins:[{name:'engine',setup(b){b.onResolve({filter:/^@dreamfactory\/engine\//},a=>({path:path.resolve('vendor/dreamrefactory/engine/src',a.path.replace('@dreamfactory/engine/','')+'.ts')}));}}]});
const {fixture,createNeutralSaveTemplate,parseRestoredSave}=await import('../.build/tests/save-codec.mjs');
test('complete restoration globals survive round trip',()=>{const save=parseRestoredSave(fixture());const globals=new Map([...save.numGlobals,...save.strGlobals]);assert.equal(globals.get('mission'),2);assert.equal(globals.get('a_long_custom_global'),'retained');});
test('corrupt and truncated restoration trailers are rejected',()=>{const good=fixture();const bad=good.slice();bad[bad.length-30]^=1;assert.throws(()=>parseRestoredSave(bad));assert.throws(()=>parseRestoredSave(good.slice(0,-7)));});
test('the authored legacy envelope parses without an extension',()=>{assert.doesNotThrow(()=>parseRestoredSave(createNeutralSaveTemplate()));});
