#!/usr/bin/env python3
"""Copy the pinned DreamFactory command table into the Go decoder."""
from pathlib import Path
import json, re, subprocess
root=Path(__file__).resolve().parents[1]
source=(root/'vendor/dreamrefactory/engine/src/df/opcodes.ts').read_text().split('export const OPCODES:',1)[1]
entries=re.findall(r'\[(\d+), "([^"]*)"\]',source)
if len(entries)!=351 or len({n for n,_ in entries})!=351 or len({s for _,s in entries})!=351:
    raise SystemExit('Pinned opcode table changed')
out=root/'internal/df/opcodes.go'
out.write_text('// Code generated by tools/generate-opcodes.py; DO NOT EDIT.\n// DreamFactory command IDs from M3tox/DFET and Daniel Hobi/dreamREfactory (GPL-3.0).\npackage df\n\nvar Opcodes = map[uint16]string{\n'+''.join(f'{n}: {json.dumps(s)},\n' for n,s in entries)+'}\n')
subprocess.run(['gofmt','-w',str(out)],check=True)
